### ISSUE TITLE
panic: unable to delete version 544000 with 1 active readers

### ISSUE THREAD

**Issue by kiennd** [NibiruChain/nibiru#1216]
i'm running validator , sometime node got interrupt with error message: 

```Mar 03 03:46:02 instance-2 nibid[402495]: 3:46AM INF executed block height=544103 module=state num_invalid_txs=0 num_valid_txs=5
Mar 03 03:46:02 instance-2 nibid[402495]: panic: unable to delete version 544000 with 1 active readers
Mar 03 03:46:02 instance-2 nibid[402495]: goroutine 130 [running]:
Mar 03 03:46:02 instance-2 nibid[402495]: github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).PruneStores(0xc000c82f70, 0x1, {0x0?, 0x0?, 0x28fd2b8?})
Mar 03 03:46:02 instance-2 nibid[402495]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.12/store/rootmulti/store.go:454 +0x285
Mar 03 03:46:02 instance-2 nibid[402495]: github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc000c82f70)
Mar 03 03:46:02 instance-2 nibid[402495]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.12/store/rootmulti/store.go:423 +0x1ab
Mar 03 03:46:02 instance-2 nibid[402495]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc000b76e00)
Mar 03 03:46:02 instance-2 nibid[402495]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.12/baseapp/abci.go:317 +0x1e6
Mar 03 03:46:02 instance-2 nibid[402495]: github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc000d9b680)
Mar 03 03:46:02 instance-2 nibid[402495]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/abci/client/local_client.go:264 +0xb6
Mar 03 03:46:02 instance-2 nibid[402495]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x50?)
Mar 03 03:46:02 instance-2 nibid[402495]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/proxy/app_conn.go:93 +0x22
Mar 03 03:46:02 instance-2 nibid[402495]: github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc000ced130, 0x8}}, {0xc000ced140, 0xc}, 0x1, 0x84d67, {{0xc0064b2f80, ...}, ...}, ...}, ...)
Mar 03 03:46:02 instance-2 nibid[402495]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/state/execution.go:228 +0x269
Mar 03 03:46:02 instance-2 nibid[402495]: github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc000ced130, 0x8}}, {0xc000ced140, 0xc}, 0x1, 0x84d67, {{0xc0064b2f80, ...}, ...}, ...}, ...)
Mar 03 03:46:02 instance-2 nibid[402495]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/state/execution.go:180 +0x6ee
Mar 03 03:46:02 instance-2 nibid[402495]: github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000d87c00, 0x0)
Mar 03 03:46:02 instance-2 nibid[402495]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/blockchain/v0/reactor.go:400 +0xbda
Mar 03 03:46:02 instance-2 nibid[402495]: created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
Mar 03 03:46:02 instance-2 nibid[402495]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/blockchain/v0/reactor.go:112 +0x7a
```

**Comment by Unique-Divine** [comment]
Hi, thanks for submitting an issue. Can you tell us more info on:
- [ ] Your exact OS
- [ ] Which installation method you used
- [ ] What version of the binary is installed (`nibid version`)
- [ ] Any reproducibility instructions
